### ISSUE TITLE
Github tag is not released automatically

### ISSUE THREAD

**Issue by aditya81070** [mikeal/merge-release#29]
I am new to GitHub actions and trying my first workflow. I have created a sample package on npm and using `merge-release` for automatic npm version release and GitHub tab release for any push on the master branch.  The issue is that `merge-release` is publishing the npm package but it is not releasing the tag on Github. Am I missing something in following workflow file?
```yml
name: Publish to NPM
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to npm and github
        uses: mikeal/merge-release@v4.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
```

Also, I have one more question that do I need to update the version in the  `package.json` file manually?
