### ISSUE TITLE
Option to update package.json version

### ISSUE THREAD

**Issue by EmilienLeroy** [mikeal/merge-release#9]
Hi,
Is it possible to add an option to update the package.json number and commit this change before publish ?
An option like this :
```yml
    - name: Publish
      uses: mikeal/merge-release@master
      with:
        update_package: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
```
